// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transport.Infrastructure;

#nullable disable

namespace Transport.Infrastructure.Migrations
{
    [DbContext(typeof(TransportContext))]
    [Migration("20250525175228_InitialTransportMigration")]
    partial class InitialTransportMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("DriverModelVehicleModel", b =>
                {
                    b.Property<int>("DriversId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehiclesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DriversId", "VehiclesId");

                    b.HasIndex("VehiclesId");

                    b.ToTable("VehicleDrivers", (string)null);
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.DriverModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.EngineModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cylinders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Horsepower")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.PassengerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.TripModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EngineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearManufactured")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EngineId")
                        .IsUnique();

                    b.ToTable("Vehicles", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.BusModel", b =>
                {
                    b.HasBaseType("Transport.Infrastructure.Models.VehicleModel");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RouteNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Buses", (string)null);
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.CarModel", b =>
                {
                    b.HasBaseType("Transport.Infrastructure.Models.VehicleModel");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("INTEGER");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.TrainModel", b =>
                {
                    b.HasBaseType("Transport.Infrastructure.Models.VehicleModel");

                    b.Property<string>("LocomotiveType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfWagons")
                        .HasColumnType("INTEGER");

                    b.ToTable("Trains", (string)null);
                });

            modelBuilder.Entity("DriverModelVehicleModel", b =>
                {
                    b.HasOne("Transport.Infrastructure.Models.DriverModel", null)
                        .WithMany()
                        .HasForeignKey("DriversId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transport.Infrastructure.Models.VehicleModel", null)
                        .WithMany()
                        .HasForeignKey("VehiclesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.PassengerModel", b =>
                {
                    b.HasOne("Transport.Infrastructure.Models.TripModel", "Trip")
                        .WithMany("Passengers")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.VehicleModel", b =>
                {
                    b.HasOne("Transport.Infrastructure.Models.EngineModel", "Engine")
                        .WithOne("Vehicle")
                        .HasForeignKey("Transport.Infrastructure.Models.VehicleModel", "EngineId");

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.BusModel", b =>
                {
                    b.HasOne("Transport.Infrastructure.Models.VehicleModel", null)
                        .WithOne()
                        .HasForeignKey("Transport.Infrastructure.Models.BusModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.CarModel", b =>
                {
                    b.HasOne("Transport.Infrastructure.Models.VehicleModel", null)
                        .WithOne()
                        .HasForeignKey("Transport.Infrastructure.Models.CarModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.TrainModel", b =>
                {
                    b.HasOne("Transport.Infrastructure.Models.VehicleModel", null)
                        .WithOne()
                        .HasForeignKey("Transport.Infrastructure.Models.TrainModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.EngineModel", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Transport.Infrastructure.Models.TripModel", b =>
                {
                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
